version: "2.1"
services:
  plex:
    image: linuxserver/plex:latest
    container_name: plex
    restart: unless-stopped
    network_mode: host
    environment:
      - TZ=Europe/London
      - PUID=1000
      - PGID=1000
      - VERSION=latest
    volumes:
      - /var/opt/docker/plex:/config
      - /mnt/media/TV:/tv
      - /mnt/media/Films:/films
      - /mnt/media/F1:/f1
    devices:
      - "/dev/dri:/dev/dri"
